const MEMTYPE_PERSIST: u32 = 0x00;
const MEMTYPE_SCRATCH: u32 = 0x10;
const IA_MEMTYPE_INPUT: u32 = 0x02;
const IA_MEMTYPE_OUTPUT: u32 = 0x03;

pub struct IaMemInfoStruct {
    ui_size: u32,
    ui_alignment: u32,
    ui_type: u32,
    ui_placement: [u32; 2],
    ui_priority: u32,
    ui_placed: [u32; 2],
}

pub struct IaMemInfoTable {
    ui_size: u32,
    ui_alignment: u32,
    ui_type: u32,
    mem_ptr: *mut std::ffi::c_void,
}

pub struct IaInputConfig<'a> {
    ui_pcm_wd_sz: u32,
    ui_effect: i32,
    ui_target_loudness: [i32; 2],
    ui_mhas_flag: i32,
    ui_raw_flag: i32,
    ui_cicp_layout_idx: i32,
    i_preset_id: i8,
    num_inp_bytes: i32,
    lsi_info_flag: i32,
    ei_info_flag: i32,
    sd_info_flag: i32,
    lsi_info_size: i32,
    ei_info_size: i32,
    sd_info_size: i32,
    extrn_rend_flag: i32,
    ptr_ei_buf: &'a str,
    ptr_ls_buf: &'a str,
    ptr_sd_buf: &'a str,
    ptr_ext_ren_ch_data_buf: &'a str,
    ptr_ext_ren_oam_data_buf: &'a str,
    ptr_ext_ren_hoa_data_buf: &'a str,
    ptr_ext_ren_pcm_buf: &'a str,
    ptr_maei_buf: &'a str,
    ptr_maeg_buf: &'a str,
    ptr_maes_buf: &'a str,
    ptr_maep_buf: &'a str,
    maei_flag: i32,
    maeg_flag: i32,
    maes_flag: i32,
    maep_flag: i32,
    maei_len: i32,
    maeg_len: i32,
    maes_len: i32,
    maep_len: i32,
    binaural_flag: i32,
    binaural_data_len: i32,
    ptr_brir_buf: &'a str,
    enable_resamp: i32,
    out_samp_freq: u32,
}

pub struct IaOutputConfig<'a> {
    i_samp_freq: i32,
    i_num_chan: i32,
    i_pcm_wd_sz: i32,
    i_channel_mask: i32,
    i_drc_effect: i32,
    i_target_loudness: i32,
    i_loud_norm: i32,
    num_preroll: i32,
    ui_init_done: u32,
    num_out_bytes: i32,
    i_bytes_consumed: i32,
    ui_inp_buf_size: u32,
    malloc_count: u32,
    ui_rem: u32,
    ui_proc_mem_tabs_size: u32,
    pv_ia_process_api_obj: *mut std::ffi::c_void,
    arr_alloc_memory: [*mut std::ffi::c_void; 100],
    p_lib_name: &'a str,
    p_version_num: &'a str,
    malloc_mpegh: fn(u32, u32) -> *mut std::ffi::c_void,
    free_mpegh: fn(*mut std::ffi::c_void),
    de_malloc_xc: fn(*mut std::ffi::c_void) -> *mut std::ffi::c_void,
    mem_info_table: [IaMemInfoTable; 4],
    oam_data_present: i32,
    oam_md_payload_length: i32,
    hoa_data_present: i32,
    hoa_md_payload_length: i32,
    ch_data_present: i32,
    ch_md_payload_length: i32,
    pcm_payload_length: i32,
    pcm_bit_depth: i32,
    hoa_sample_offset: i32,
    oam_sample_offset: i32,
    num_speakers: i32,
    spk_layout: i32,
    cicp_index: i32,
    is_binaural_rendering: i32,
    is_lfe: [i32; 24],
    azimuth: [i16; 24],
    elevation: [i16; 24],
}

pub struct IaMpeghdApiStruct<'a> {
    input_config: IaInputConfig<'a>,
    output_config: IaOutputConfig<'a>,
}